name: Build iOS Client

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # 允许手动触发构建

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        check-latest: true
    
    - name: Install gomobile
      run: |
        cd code
        export GOPATH=$HOME/go
        export PATH=$PATH:$GOPATH/bin
        go mod tidy
        go install golang.org/x/mobile/cmd/gomobile@latest
        go install golang.org/x/mobile/cmd/gobind@latest
        gomobile init
    
    - name: Build iOS Framework
      run: |
        cd code
        export PATH=$PATH:$(go env GOPATH)/bin
        gomobile bind -target=ios -o build/IosClient.xcframework ./ios
    
    - name: Create Release Directory
      run: |
        mkdir -p release
    
    - name: Package Framework
      run: |
        cd code/build
        zip -r ../../release/IosClient.xcframework.zip IosClient.xcframework
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: IosClient.xcframework
        path: release/IosClient.xcframework.zip