name: Build hello

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  # 允许手动触发构建

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        check-latest: true
    
    - name: Install gomobile
      run: |
        # 设置 GOPATH
        export GOPATH=$HOME/go
        export PATH=$PATH:$GOPATH/bin
        
        # 安装 gomobile 及其依赖
        go install golang.org/x/mobile/cmd/gomobile@latest
        go install golang.org/x/mobile/cmd/gobind@latest
        
        # 确保所有依赖都被下载
        go get -d golang.org/x/mobile/bind
        go get -d golang.org/x/mobile/bind/objc
        
        # 初始化 gomobile
        gomobile init
    
    - name: Build iOS Framework
      run: |
        # 确保 PATH 设置正确
        export PATH=$PATH:$(go env GOPATH)/bin
        gomobile bind -target=ios -o build/Hello.xcframework shiledp2p/hello
    
    - name: Create Release Directory
      run: |
        mkdir -p release
    
    - name: Package Framework
      run: |
        cd build
        zip -r ../release/Hello.xcframework.zip Hello.xcframework
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Hello.xcframework
        path: release/Hello.xcframework.zip 