name: iOS Framework Build

on:
  push:
    branches: [ master ]
    paths:
      - 'code/mobile/ios/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'code/mobile/ios/**'
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: macos-latest  # 使用最新的 macOS 运行器
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'  # 使用与项目相同的 Go 版本
    
    - name: Install Xcode Command Line Tools
      run: |
        xcode-select --install || true
        sudo xcode-select --switch /Applications/Xcode.app
    
    - name: Install gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@v0.0.0-20240213143359-d1f7d3436075
        go install golang.org/x/mobile/cmd/gobind@v0.0.0-20240213143359-d1f7d3436075
        export GOPATH=$(go env GOPATH)
        export PATH=$PATH:$GOPATH/bin
        gomobile init
    
    - name: Download dependencies
      run: |
        cd code
        go mod download
        go mod tidy
    
    - name: Build iOS Framework
      run: |
        cd code/mobile/ios
        chmod +x build.sh
        ./build.sh
    
    - name: Upload Framework
      uses: actions/upload-artifact@v4
      with:
        name: SimpleDemo.xcframework
        path: code/mobile/ios/SimpleDemo.xcframework
        if-no-files-found: error 