name: iOS Framework Build

on:
  push:
    branches: [ master ]
    paths:
      - 'code/mobile/ios/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'code/mobile/ios/**'
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: macos-latest  # 使用最新的 macOS 运行器
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.0'  # 使用最新的稳定版本
    
    - name: Install Xcode Command Line Tools
      run: |
        xcode-select --install || true
        sudo xcode-select --switch /Applications/Xcode.app
    
    - name: Setup Go environment
      run: |
        echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        go env
    
    - name: Setup Go module
      run: |
        cd code
        if [ ! -f go.mod ]; then
          go mod init shiledp2p
        fi
        go mod tidy
    
    - name: Install gomobile
      run: |
        cd code
        go install golang.org/x/mobile/cmd/gomobile@latest
        go install golang.org/x/mobile/cmd/gobind@latest
        gomobile init -v
    
    - name: Verify gomobile installation
      run: |
        cd code
        which gomobile
        which gobind
        gomobile version
        go list -f '{{.Dir}}' golang.org/x/mobile/bind
    
    - name: Download dependencies
      run: |
        cd code
        go mod download
        go mod tidy
        go list -m all
    
    - name: Build iOS Framework
      run: |
        cd code/mobile/ios
        chmod +x build.sh
        ./build.sh
    
    - name: Upload Framework
      uses: actions/upload-artifact@v4
      with:
        name: SimpleDemo.xcframework
        path: code/mobile/ios/SimpleDemo.xcframework
        if-no-files-found: error 