name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.8'
        cache: true
        check-latest: true
    
    - name: Switch Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode_15.2.app
        xcodebuild -version
    
    - name: Verify Go Version
      run: |
        go version
        which go
    
    - name: Build iOS Framework
      run: |
        cd code/mobile/ios
        chmod +x build.sh
        ./build.sh
