name: iOS Framework Build

on:
  push:
    branches: [ main ]
    paths:
      - 'code/mobile/ios/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'code/mobile/ios/**'
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: macos-latest  # 使用最新的 macOS 运行器
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'  # 使用与项目相同的 Go 版本
    
    - name: Install gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        go install golang.org/x/mobile/cmd/gobind@latest
        gomobile init
    
    - name: Download dependencies
      working-directory: code
      run: |
        go mod download
        go mod tidy
    
    - name: Build iOS Framework
      working-directory: code/mobile/ios
      run: |
        chmod +x build.sh
        ./build.sh
    
    - name: Upload Framework
      uses: actions/upload-artifact@v4
      with:
        name: ShileP2P.framework
        path: code/mobile/ios/ShileP2P.framework
        if-no-files-found: error 